'''
    深度学习子界面
'''

from PySide6 import QtCore, QtGui, QtWidgets

# .ui文件转换得到
class Ui_DeepLearning(object):
    def setupUi(self, DeepLearning):
        DeepLearning.setObjectName("DeepLearning")
        DeepLearning.resize(873, 889)
        DeepLearning.setMinimumSize(QtCore.QSize(500, 400))
        self.DeepLearning_Frame = QtWidgets.QFrame(DeepLearning)
        self.DeepLearning_Frame.setGeometry(QtCore.QRect(0, 40, 700, 600))
        self.DeepLearning_Frame.setMinimumSize(QtCore.QSize(500, 400))
        self.DeepLearning_Frame.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.DeepLearning_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DeepLearning_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DeepLearning_Frame.setObjectName("DeepLearning_Frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.DeepLearning_Frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DeepLearning_title_frame = QtWidgets.QFrame(self.DeepLearning_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.DeepLearning_title_frame.sizePolicy().hasHeightForWidth())
        self.DeepLearning_title_frame.setSizePolicy(sizePolicy)
        self.DeepLearning_title_frame.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.DeepLearning_title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DeepLearning_title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DeepLearning_title_frame.setObjectName("DeepLearning_title_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.DeepLearning_title_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.DeepLearning_system_frame = QtWidgets.QFrame(self.DeepLearning_title_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.DeepLearning_system_frame.sizePolicy().hasHeightForWidth())
        self.DeepLearning_system_frame.setSizePolicy(sizePolicy)
        self.DeepLearning_system_frame.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.DeepLearning_system_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DeepLearning_system_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DeepLearning_system_frame.setObjectName("DeepLearning_system_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.DeepLearning_system_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DeepLearning_icon = QtWidgets.QFrame(self.DeepLearning_system_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeepLearning_icon.sizePolicy().hasHeightForWidth())
        self.DeepLearning_icon.setSizePolicy(sizePolicy)
        self.DeepLearning_icon.setMinimumSize(QtCore.QSize(85, 85))
        self.DeepLearning_icon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DeepLearning_icon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DeepLearning_icon.setObjectName("DeepLearning_icon")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.DeepLearning_icon)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.DeepLearning_Icon = QtWidgets.QLabel(self.DeepLearning_icon)
        self.DeepLearning_Icon.setMinimumSize(QtCore.QSize(85, 85))
        self.DeepLearning_Icon.setStyleSheet("")
        self.DeepLearning_Icon.setText("")
        self.DeepLearning_Icon.setPixmap(QtGui.QPixmap("Resource/img/logo.png"))
        self.DeepLearning_Icon.setScaledContents(True)
        self.DeepLearning_Icon.setObjectName("DeepLearning_Icon")
        self.verticalLayout_4.addWidget(self.DeepLearning_Icon, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.DeepLearning_icon, 0, QtCore.Qt.AlignTop)
        self.DeepLearning_title = QtWidgets.QFrame(self.DeepLearning_system_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeepLearning_title.sizePolicy().hasHeightForWidth())
        self.DeepLearning_title.setSizePolicy(sizePolicy)
        self.DeepLearning_title.setMinimumSize(QtCore.QSize(130, 50))
        self.DeepLearning_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DeepLearning_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DeepLearning_title.setObjectName("DeepLearning_title")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.DeepLearning_title)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Machinelearning_Title = QtWidgets.QLabel(self.DeepLearning_title)
        self.Machinelearning_Title.setMinimumSize(QtCore.QSize(256, 46))
        self.Machinelearning_Title.setStyleSheet("")
        self.Machinelearning_Title.setText("")
        self.Machinelearning_Title.setPixmap(QtGui.QPixmap("Resource/img/title.jpg"))
        self.Machinelearning_Title.setScaledContents(True)
        self.Machinelearning_Title.setObjectName("Machinelearning_Title")
        self.horizontalLayout_3.addWidget(self.Machinelearning_Title)
        self.horizontalLayout.addWidget(self.DeepLearning_title)
        self.verticalLayout_3.addWidget(self.DeepLearning_system_frame)
        self.DeepLearning_option_frame = QtWidgets.QFrame(self.DeepLearning_title_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.DeepLearning_option_frame.sizePolicy().hasHeightForWidth())
        self.DeepLearning_option_frame.setSizePolicy(sizePolicy)
        self.DeepLearning_option_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DeepLearning_option_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DeepLearning_option_frame.setObjectName("DeepLearning_option_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.DeepLearning_option_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.deeplearning = QtWidgets.QLabel(self.DeepLearning_option_frame)
        self.deeplearning.setStyleSheet("font: 75 9pt \"Fixedsys\";")
        self.deeplearning.setObjectName("deeplearning")
        self.horizontalLayout_2.addWidget(self.deeplearning, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.DeepLearning_option_frame)
        self.verticalLayout.addWidget(self.DeepLearning_title_frame)
        self.DeepLearning_button_frame = QtWidgets.QFrame(self.DeepLearning_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.DeepLearning_button_frame.sizePolicy().hasHeightForWidth())
        self.DeepLearning_button_frame.setSizePolicy(sizePolicy)
        self.DeepLearning_button_frame.setStyleSheet("")
        self.DeepLearning_button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DeepLearning_button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DeepLearning_button_frame.setObjectName("DeepLearning_button_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.DeepLearning_button_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.DeepLearning_gridLayout = QtWidgets.QGridLayout()
        self.DeepLearning_gridLayout.setObjectName("DeepLearning_gridLayout")
        self.CNN = PushButton(self.DeepLearning_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CNN.sizePolicy().hasHeightForWidth())
        self.CNN.setSizePolicy(sizePolicy)
        self.CNN.setMinimumSize(QtCore.QSize(150, 80))
        self.CNN.setObjectName("CNN")
        self.DeepLearning_gridLayout.addWidget(self.CNN, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.DeepLearning_Others = PushButton(self.DeepLearning_button_frame)
        self.DeepLearning_Others.setMinimumSize(QtCore.QSize(150, 80))
        self.DeepLearning_Others.setObjectName("DeepLearning_Others")
        self.DeepLearning_gridLayout.addWidget(self.DeepLearning_Others, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.DeepLearning_gridLayout)
        self.verticalLayout.addWidget(self.DeepLearning_button_frame)

        self.retranslateUi(DeepLearning)
        QtCore.QMetaObject.connectSlotsByName(DeepLearning)

    def retranslateUi(self, DeepLearning):
        _translate = QtCore.QCoreApplication.translate
        DeepLearning.setWindowTitle(_translate("DeepLearning", "Form"))
        self.deeplearning.setText(_translate("DeepLearning", "深度学习算法教学演示"))
        self.CNN.setText(_translate("DeepLearning", "卷积神经网络"))
        self.DeepLearning_Others.setText(_translate("DeepLearning", "敬请期待"))
from qfluentwidgets import PushButton

from PySide6.QtWidgets import QWidget

class DeepLearningInterface(QWidget, Ui_DeepLearning):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

